# Generated by Django 2.1.7 on 2020-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_text',
            field=models.TextField(default='max_length=500', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='max_length=800', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(max_length=200),
        ),
    ]
